### ISSUE TITLE
Ajuda para rodar Decidim via Docker - Problemas com migrações e permissões

### ISSUE THREAD

**Issue by hermesalvesbr** [octree-gva/docker#7]
Olá @froger,

Primeiramente, quero expressar minha gratidão pelo seu trabalho no Decidim e sua contribuição para o mundo open-source. Eu sou do Brasil e estou tentando rodar o Decidim localmente usando Docker, mas estou enfrentando alguns problemas. Seria incrível se você pudesse me ajudar ou orientar sobre como resolver esses erros.

Aqui está o meu arquivo docker-compose.yml:
```services:
  decidim:
    image: hfroger/decidim:0.29.0
    container_name: decidim
    ports:
      - "8080:8080"
    volumes:
      - ./storage:/home/decidim/app/storage
      - ./db/migrate:/home/decidim/app/db/migrate
      - ./tmp:/home/decidim/app/tmp
      - ./log:/home/decidim/app/log
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: your_secret_key_here
      DEVISE_SECRET_KEY: your_devise_secret_key_here
      DECIDIM_SYSTEM_EMAIL: system@example.org
      DECIDIM_SYSTEM_PASSWORD: system_password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: decidim_production
      DB_USER: decidim
      DB_PASSWORD: decidim_password
      DATABASE_URL: "postgres://decidim:decidim_password@db:5432/decidim_production"
      RAILS_SERVE_STATIC_FILES: "false"
      RAILS_FORCE_SSL: "false"
      SMTP_ADDRESS: "mailer"
      SMTP_PORT: "25"
      SMTP_AUTHENTICATION: "none"
      QUEUE_ADAPTER: "async"
  db:
    image: postgres:15
    container_name: decidim_db
    environment:
      POSTGRES_DB: decidim_production
      POSTGRES_USER: decidim
      POSTGRES_PASSWORD: decidim_password
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"

volumes:
  storage:
  pg_data:
```

Aqui está o erro que estou recebendo:
``` 
✔ Network decidim-araripina_default          Created
✔ Container decidim                          Created
✔ Container decidim-araripina-mailcatcher-1  Created
✔ Container decidim_db                       Created
Attaching to decidim, mailcatcher-1, decidim_db
decidim        | Container initializing.
decidim        | Running /docker-entrypoint.d scripts
decidim        | /docker-entrypoint.d/05_clean_history: 12: cannot create /var/log/wtmp: Permission denied
decidim_db     | 2024-09-29 02:01:06.735 UTC [29] LOG:  database system was shut down at 2024-09-29 01:58:59 UTC
decidim_db     | 2024-09-29 02:01:06.741 UTC [1] LOG:  database system is ready to accept connections
decidim        | wait-for-it: db:5432 is available after 0 seconds
decidim        | ✅ database is up
decidim        | The Gemfile's dependencies are satisfied
decidim        | ✅ Gems in Gemfiles are installed
decidim        | ✅ Migrations are all up
decidim_db     | 2024-09-29 02:01:17.870 UTC [36] ERROR:  relation "decidim_system_admins" does not exist
decidim        | PG::UndefinedTable: ERROR:  relation "decidim_system_admins" does not exist
decidim exited with code 1
```

### O que já tentei:

1. Verifiquei as permissões nos volumes e diretórios mapeados.
2. Tentei rodar manualmente as migrações, mas continuo recebendo o erro de que a tabela decidim_system_admins não existe.

Você poderia me orientar sobre o que estou fazendo de errado ou se há algo específico que preciso configurar no Docker para rodar o Decidim corretamente? Qualquer dica seria muito bem-vinda!

Agradeço desde já por seu tempo e pela sua dedicação ao projeto!

**Comment by SagarChandra07** [comment]
I think this will help you.

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme

you may need to install the c compiler

**Comment by rsdeus** [comment]
Olá @hermesalvesbr, consegue rodar o comando `rails db:migrate:status | grep down` e verificar quais são as migrações que estão faltando? 
Pelo erro que você apresentou provavelmente está faltando o arquivo `20160919105637_devise_create_decidim_admins.rb` mas podem haver outros modelos faltantes.

**Comment by hermesalvesbr** [comment]
Obrigado pelo retorno @rsdeus , o container encerra antes que eu consiga explorar mais logs e etc:

```CONTAINER ID   IMAGE                    COMMAND                   CREATED          STATUS          PORTS                                                 NAMES
fab27a316022   hfroger/decidim:0.29.0   "/bin/sh -c \"./bin/d…"   10 seconds ago   Up 10 seconds   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp             decidim
e186acc4d628   schickling/mailcatcher   "sh -c 'mailcatcher …"    3 days ago       Up 10 seconds   1025/tcp, 0.0.0.0:1080->1080/tcp, :::1080->1080/tcp   decidim-araripina-mailcatcher-1
2ced8303488e   postgres:15              "docker-entrypoint.s…"    3 days ago       Up 10 seconds   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp             decidim_db
➜  decidim-araripina git:(feat/better-decidim-docker) ✗ docker exec -it decidim /bin/bash
Error response from daemon: container fab27a3160220aeef13f35bff442ae79cb9a145bb0c068d5c635a6b0ce4c77e5 is not running
➜  decidim-araripina git:(feat/better-decidim-docker) ✗ docker exec -it decidim /bin/bash
decidim@ea6faf01f6d5:~$ ls
Dockerfile          README.md  config.ru                    log                storage
Gemfile             Rakefile   db                           package-lock.json  test
Gemfile.lock        app        docker-compose-etherpad.yml  package.json       tmp
LICENSE-AGPLv3.txt  bin        docker-compose.yml           postcss.config.js  tsconfig.json
Procfile.dev        config     lib                          public             vendor
decidim@ea6faf01f6d5:~$ %
➜  decidim-araripina git:(feat/better-decidim-docker) ✗ docker exec -it decidim /bin/bash
decidim@ea6faf01f6d5:~$ rails db:migrate:status | grep down
decidim@ea6faf01f6d5:~$ rails db:migrate:status | grep down
```

O retorno do container completo é esse: 

```
docker compose up
[+] Running 3/0
 ✔ Container decidim_db                       Created                                          0.0s
 ✔ Container decidim-araripina-mailcatcher-1  C...                                             0.0s
 ✔ Container decidim                          Created                                          0.0s
Attaching to decidim, mailcatcher-1, decidim_db
decidim_db     |
decidim_db     | PostgreSQL Database directory appears to contain a database; Skipping initialization
decidim_db     |
decidim_db     | 2024-10-02 17:53:41.986 UTC [1] LOG:  starting PostgreSQL 15.8 (Debian 15.8-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
decidim_db     | 2024-10-02 17:53:42.074 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
decidim_db     | 2024-10-02 17:53:42.074 UTC [1] LOG:  listening on IPv6 address "::", port 5432
decidim_db     | 2024-10-02 17:53:42.077 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
decidim_db     | 2024-10-02 17:53:42.081 UTC [30] LOG:  database system was shut down at 2024-10-02 17:53:38 UTC
decidim_db     | 2024-10-02 17:53:42.084 UTC [1] LOG:  database system is ready to accept connections
decidim        | Container initializing.
decidim        | Running /docker-entrypoint.d scripts
decidim        | /docker-entrypoint.d/05_clean_history: 12: cannot create /var/log/wtmp: Permission denied
decidim        | /docker-entrypoint.d/05_clean_history:
decidim        |    Clean history from file: /var/log/wtmp.
decidim        | run-parts: /docker-entrypoint.d/05_clean_history exited with return code 2
decidim        | /docker-entrypoint.d/10_remove_pid:
decidim        |     ✅  Puma pid is removed
decidim        | /docker-entrypoint.d/11_deface_precompile:
decidim        |     ➡️ skip deface
mailcatcher-1  | Starting MailCatcher v0.8.2
decidim        | /docker-entrypoint.d/15_wait_for_it:
mailcatcher-1  | ==> smtp://0.0.0.0:1025
mailcatcher-1  | ==> http://0.0.0.0:1080
decidim        | wait-for-it: waiting 15 seconds for db:5432
decidim        | wait-for-it: db:5432 is available after 0 seconds
decidim        |     ✅ database is up
decidim        | /docker-entrypoint.d/35_bundle_check:
decidim        | The Gemfile's dependencies are satisfied
decidim        |     ✅ Gems in Gemfiles are installed
decidim        |     ✅ Migrations are all up
decidim        | /docker-entrypoint.d/45_template:10:in `write': Permission denied @ rb_sysopen - /etc/motd (Errno::EACCES)
decidim        |        from /docker-entrypoint.d/45_template:10:in `block in <main>'
decidim        |        from /docker-entrypoint.d/45_template:6:in `chdir'
decidim        |        from /docker-entrypoint.d/45_template:6:in `<main>'
decidim        | Setup templates
decidim        | run-parts: /docker-entrypoint.d/45_template exited with return code 1
decidim        | Loading production environment (Rails 7.0.8.4)
decidim        | Switch to inspect mode.
decidim        |   if ENV["DECIDIM_SYSTEM_EMAIL"].present? && ENV["DECIDIM_SYSTEM_PASSWORD"].present?
decidim        |       admin = Decidim::System::Admin.where(email: ENV["DECIDIM_SYSTEM_EMAIL"]).first_or_initialize(
decidim        |             email: ENV["DECIDIM_SYSTEM_EMAIL"],
decidim        |             password: ENV["DECIDIM_SYSTEM_PASSWORD"],
decidim        |             password_confirmation: ENV["DECIDIM_SYSTEM_PASSWORD"]
decidim        |         )
decidim        |       admin.password_confirmation = admin.password = ENV["DECIDIM_SYSTEM_PASSWORD"]
decidim        |       admin.save
decidim        |          puts "/docker-entrypoint.d/50_upsert-sysadmin:"
decidim        |       puts "    ✅ /system DECIDIM_SYSTEM_EMAIL account updated."
decidim        |     end
decidim_db     | 2024-10-02 17:53:51.898 UTC [38] ERROR:  relation "decidim_system_admins" does not exist at character 491
decidim_db     | 2024-10-02 17:53:51.898 UTC [38] STATEMENT:  SELECT a.attname, format_type(a.atttypid, a.atttypmod),
decidim_db     |               pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
decidim_db     |               c.collname, col_description(a.attrelid, a.attnum) AS comment,
decidim_db     |               attgenerated as attgenerated
decidim_db     |          FROM pg_attribute a
decidim_db     |          LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
decidim_db     |          LEFT JOIN pg_type t ON a.atttypid = t.oid
decidim_db     |          LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
decidim_db     |         WHERE a.attrelid = '"decidim_system_admins"'::regclass
decidim_db     |           AND a.attnum > 0 AND NOT a.attisdropped
decidim_db     |         ORDER BY a.attnum
decidim_db     |
decidim        | /home/decidim/app/vendor/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `exec': PG::UndefinedTable: ERROR:  relation "decidim_system_admins" does not exist (ActiveRecord::StatementInvalid)
decidim        | LINE 9:  WHERE a.attrelid = '"decidim_system_admins"'::regclass
decidim        |                             ^
decidim        |
decidim        | /home/decidim/app/vendor/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `exec': ERROR:  relation "decidim_system_admins" does not exist (PG::UndefinedTable)
decidim        | LINE 9:  WHERE a.attrelid = '"decidim_system_admins"'::regclass
decidim        |                             ^
decidim        |
decidim        |
decidim exited with code 1
```

**Comment by hermesalvesbr** [comment]
Conseguimos fazer rodar, mas agora enroscamos na criação da organização. Vou mandar meu docker-compose.yml , pois a intenção é ajudar outras pessoas:

```
services:
  decidim:
    image: hfroger/decidim:0.29.1
    entrypoint: bin/docker-entrypoint
    command: bundle exec rails s -b 0.0.0.0
    restart: unless-stopped
    user: root
    volumes:
      - storage:/home/decidim/app/storage
      - bundle:/home/decidim/app/vendor
      - public:/home/decidim/app/public
      - db:/home/decidim/app/db
      - config:/home/decidim/app/config
    environment:
      DECIDIM_SYSTEM_EMAIL: "admin@example.org"
      DECIDIM_SYSTEM_PASSWORD: "my_insecure_password"
      DECIDIM_FORCE_SSL: "false"
      DATABASE_URL: "postgres://decidim:my_insecure_password@pg:5432/decidim"
      REDIS_URL: "redis://redis:6379"
      RAILS_SERVE_STATIC_FILES: "false"
      #RAILS_FORCE_SSL: "false"
      SMTP_ADDRESS: "mailer"
      SMTP_PORT: "25"
      SMTP_AUTHENTICATION: "none"
      QUEUE_ADAPTER: "async"
      SECRET_KEY_BASE: "cOhUG6GV6xMFrDoSwoiF5WtcNNMmtMfl"
    ports:
      - 3000:3000
    depends_on:
      - pg
      - mailer
  pg:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "my_insecure_password"
      POSTGRES_USER: "decidim"
      POSTGRES_DB: "decidim"
  redis:
    image: redis
    volumes:
      - redis-data:/data
  mailer:
    image: tophfr/mailcatcher
    restart: unless-stopped
    ports:
      # SMTP port is 25, webinterface is on 80
      - 1080:80

volumes:
  pg-data: {}
  redis-data: {}
  storage: {}
  bundle: {}
  public: {}
  db: {}
  config: {}

```
![Imagem do WhatsApp de 2024-10-04 à(s) 07 25 11_4e027ee9](https://github.com/user-attachments/assets/7c5fc258-7a08-472a-a814-7e4afce0262c)

Mesmo com SECRET_KEY_BASE definido, e caso não preencha o campo, mesmo em branco. Ele  trava como obrigatório o campo PASSWORD do smtp mail. 

**You need to define SECRET_KEY_BASE environment variable to be able to save this field**
